{% set version = '0.6-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lavaan
  version: {{ version|replace("-", "_") }}

source:
  fn: lavaan_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lavaan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lavaan/lavaan_{{ version }}.tar.gz
  sha256: 229277d0c78bdbd252a6b016ad6aa4621e6b4dd0d1acc3b201cbf5128da9154c

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
  run:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm

test:
  commands:
    - $R -e "library('lavaan')"           # [not win]
    - "\"%R%\" -e \"library('lavaan')\""  # [win]

about:
  home: http://lavaan.org
  license: GPL (>= 2)
  summary: Fit a variety of latent variable models, including confirmatory factor analysis, structural
    equation modeling and latent growth curve models.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
