{% set version = '0.6-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lavaan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lavaan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lavaan/lavaan_{{ version }}.tar.gz
  sha256: bffb89d7fb70f6bde5c984009803b3ab9b9802cc2608d2acb1f887b0a7298843

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm

  run:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lavaan')"           # [not win]
    - "\"%R%\" -e \"library('lavaan')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://lavaan.org
  license: GPL (>= 2)
  summary: Fit a variety of latent variable models, including confirmatory factor analysis, structural
    equation modeling and latent growth curve models.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lavaan
# Title: Latent Variable Analysis
# Version: 0.6-3
# Authors@R: c(person(given   = "Yves", family = "Rosseel", role    = c("aut", "cre"), email   = "Yves.Rosseel@UGent.be", comment = c(ORCID = "0000-0002-4129-4477")), person(given = "Daniel", family = "Oberski", role = "ctb", email = "daniel.oberski@gmail.com"), person(given = "Jarrett", family = "Byrnes",  role = "ctb", email = "byrnes@nceas.ucsb.edu"), person(given = "Leonard", family = "Vanbrabant", role = "ctb", email = "Leonard.Vanbrabant@ugent.be"), person(given = "Victoria", family = "Savalei", role = "ctb", email = "vsavalei@ubc.ca"), person(given = "Ed", family = "Merkle", role = "ctb", email = "merklee@missouri.edu"), person(given = "Michael", family = "Hallquist", role = "ctb", email = "michael.hallquist at gmail.com"), person(given = "Mijke", family = "Rhemtulla", role = "ctb", email = "mijke@ku.edu"), person(given = "Myrsini", family = "Katsikatsou", role = "ctb", email = "mirtok2@gmail.com"), person(given = "Mariska", family = "Barendse", role = "ctb", email = "m.t.barendse@rug.nl"), person(given = "Michael", family = "Chow", role = "ctb", email = "machow@princeton.edu"), person(given = c("Terrence","D."), family = "Jorgensen", role = "ctb", comment = c(ORCID = "0000-0001-5111-6773")) )
# Description: Fit a variety of latent variable models, including confirmatory factor analysis, structural equation modeling and latent growth curve models.
# Depends: R(>= 3.4)
# Imports: methods, stats4, stats, utils, graphics, MASS, mnormt, pbivnorm, numDeriv
# Suggests: testthat
# License: GPL (>= 2)
# LazyData: yes
# ByteCompile: true
# URL: http://lavaan.org
# NeedsCompilation: no
# Packaged: 2018-09-22 14:15:39 UTC; yves
# Author: Yves Rosseel [aut, cre] (<https://orcid.org/0000-0002-4129-4477>), Daniel Oberski [ctb], Jarrett Byrnes [ctb], Leonard Vanbrabant [ctb], Victoria Savalei [ctb], Ed Merkle [ctb], Michael Hallquist [ctb], Mijke Rhemtulla [ctb], Myrsini Katsikatsou [ctb], Mariska Barendse [ctb], Michael Chow [ctb], Terrence D. Jorgensen [ctb] (<https://orcid.org/0000-0001-5111-6773>)
# Maintainer: Yves Rosseel <Yves.Rosseel@UGent.be>
# Repository: CRAN
# Date/Publication: 2018-09-22 23:20:07 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
