travis:
  secure:
    BINSTAR_TOKEN: G58nOXjio/Gh901XxboC1I803bNFNrwsGHPFQMdgd9Vf/092fJUmXBgOV98sGYHWJemOzLxjcGIAWbsqlbIF2e/N9sCdij0Wgq9cayqi+Lq1sb4JswdL7GaNEP95MmXlab1b/i8bkNrm145XXRiann7DhCSxb2xwLQICqp9+Cm+d5tpStQhViba7/GwGig0sdfNYPUiYBoiAPZLcrKiQWXNJsyMXwexmlSo1NFGDT5QPpJxN9ATY5ml+09PuDOIql/L5wonTPyLwqFw1+hsDp4rIEJftVq7wAgV2ZjScxYk298bOzTBHx4NvVWO5w0vetpsiLn3v+CmHG7O0l31Fy1kIx2UN1fG4dzEg3pd3b/mQxn+mrJS1jUiUY7kZ7nYB4w6SwwW9mGOtoM4EJ57RqGGlxsKO++/B335OpraWy982kk0TOsiRCF41Um8quvlFLry95nfCSQwZLVZTO6Qs+u9qjjoAnvmUH2kaY248CKk/BY8Ov14A/x+d1kXVIYGVmlyzpw5B/VpNm7Dx5GF0AdGW98K8WXghGcAXKIC2u5siBxK5xTWvIa8wkUxhZNyKt6eYEowu7v9cmrVBCVqrP4V6xvmPBn+1y6m0Y2S7JR5DUA1psSQGGEkNPhIm6xybQB1EMPf5IqpQ60t5cgLH7zMjJEI8W7/SK/n0TZxqgWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
